routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('login/facebook', 'Auth\SocialAuthController@redirect')->name('login.redirect.facebook');
Route::get('login/facebook/callback', 'Auth\SocialAuthController@callback')->name('login.callback.facebook');
Route::get('login/google', 'Auth\SocialAuthController@redirect')->name('login.redirect.google');
Route::get('login/google/callback', 'Auth\SocialAuthController@callback')->name('login.callback.google');
Route::post('login/social/email', 'Auth\SocialAuthController@addEmail')->name('login.social.email');
Route::post('login/telegram', 'Auth\SocialAuthController@addTelegramId')->name('login.telegram');

// teacher
Route::prefix('teachers')->name('teacher.')->group(function() {

    Route::namespace('Teacher')->middleware(['teacher', 'verified'])->group(function() {

        Route::get('profile/create', 'ProfileController@create')->name('profile.create');
        Route::post('profile', 'ProfileController@store')->name('profile.store');

        Route::middleware(['teacher.profile.exist'])->group(function (){

            Route::get('/cabinet', 'CabinetController@index')->name('cabinet.index');
            // profile
            Route::get('profile', 'ProfileController@index')->name('profile.index');
            Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
            Route::put('profile', 'ProfileController@update')->name('profile.update');

            // invite student
            Route::get('invite', 'InviteController@index')->name('invite.index');
            Route::post('invite', 'InviteController@store')->name('invite.store');
            Route::delete('invite/{invite}', 'InviteController@destroy')->name('invite.destroy');

            // student request
            Route::get('students/requests', 'StudentRequestController@index')->name('students.requests.index');
            Route::put('students/requests/{teacherRequests}', 'StudentRequestController@update')->name('students.requests.update');

            // courses
            Route::get('courses/my-courses', 'CourseController@myCourses')->name('courses.my-courses');
            Route::get('courses', 'CourseController@index')->name('courses.index');
            Route::get('courses/create', 'CourseController@create')->name('courses.create');
            Route::get('courses/{course}', 'CourseController@show')->name('courses.show');
            Route::post('courses', 'CourseController@store')->name('courses.store');

            //lessons
            Route::get('courses/{course}/chapters/{chapter}/lessons/create', 'LessonController@create')->name('lessons.create');
            Route::get('courses/{course}/chapters/{chapter}/lessons/{lesson}/edit', 'LessonController@edit')->name('lessons.edit');
            Route::post('courses/{course}/chapters/{chapter}/lessons', 'LessonController@store')->name('lessons.store');
            Route::put('courses/{course}/chapters/{chapter}/lessons/{lesson}', 'LessonController@update')->name('lessons.update');

            // individual lessons themes
            Route::resource('private/themes', 'IndividualLessonThemeController')
                ->only('index', 'store', 'show', 'update', 'destroy')
                ->middleware(['throttle:60,1', 'teacher']);

            // individual lessons
            Route::get('private/lessons', 'IndividualLessonsController@index')->name('individual.index');
            Route::get('private/lessons/create', 'IndividualLessonsController@create')->name('individual.create');
            Route::get('private/lessons/{lesson}/edit', 'IndividualLessonsController@edit')->name('individual.edit');
            Route::put('private/lessons/{lesson}', 'IndividualLessonsController@update')->name('individual.update')->middleware('throttle:30,1');
            Route::post('private/lessons', 'IndividualLessonsController@store')->name('individual.store');
            Route::delete('private/lessons/{lesson}', 'IndividualLessonsController@destroy')->name('individual.destroy');
            Route::post('private/lessons/{lesson}/group', 'IndividualLessonsController@addLessonToGroup')->name('individual.addLessonToGroup');
            Route::post('private/lessons/{lesson}/student', 'IndividualLessonsController@addLessonToStudent')->name('individual.addLessonToStudent');
            Route::put('private/lessons/{lesson}/activate', 'IndividualLessonsController@activate')->name('individual.activate')->middleware('throttle:30,1');
            Route::post('private/lessons/{lesson}/duplicate', 'IndividualLessonsController@duplicate')->name('individual.duplicate')->middleware('throttle:15,1');
            Route::delete('private/lessons/{lesson}/detach/{clientId}', 'IndividualLessonsController@detachStudent')->name('individual.detachStudent')->middleware('throttle:30,1');

            // groups
            Route::get('groups', 'GroupController@index')->name('groups.index');
            Route::post('groups', 'GroupController@store')->name('groups.store');
            Route::put('groups/{group}', 'GroupController@update')->name('groups.update');
            Route::delete('groups/{group}', 'GroupController@destroy')->name('groups.destroy');
            Route::delete('groups/{group}/detach/{clientId}', 'GroupController@detachClient')->name('groups.detachClient');
            Route::post('groups/{group}/attach/{clientId}', 'GroupController@attachClient')->name('groups.attachClient');

            //course lessons
            Route::get('courses/{course}/chapters/{chapter}/lessons/create', 'LessonController@create')->name('lessons.create');
            Route::get('courses/{course}/chapters/{chapter}/lessons/{lesson}/edit', 'LessonController@edit')->name('lessons.edit');
            Route::post('courses/{course}/chapters/{chapter}/lessons', 'LessonController@store')->name('lessons.store');
            Route::put('courses/{course}/chapters/{chapter}/lessons/{lesson}', 'LessonController@update')->name('lessons.update');
        });
    });


    Auth::routes(['verify' => true]);
});

// client
Route::middleware(['client', 'verified'])->namespace('Client')->group(function () {
    Route::get('cabinet', 'CabinetController@index')->name('cabinet.index');

    // profile
    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/create', 'ProfileController@create')->name('profile.create');
    Route::post('profile', 'ProfileController@store')->name('profile.store');
    Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('profile', 'ProfileController@update')->name('profile.update');

    // courses
    Route::get('courses/my-courses', 'CourseController@show')->name('courses.show');
    Route::get('courses', 'CourseController@index')->name('courses.index');

    // teachers
    Route::get('teachers', 'TeacherController@index')->name('teachers.index');
    Route::get('teachers/{teacher}', 'TeacherController@show')->name('teachers.show');
    Route::post('teachers/request', 'TeacherController@requestToTeacher')->name('teachers.requestToTeacher');

    // my-lessons
    Route::get('my-lessons', 'MyLessonController@index')->name('my-lessons.index');
});

Auth::routes(['verify' => true]);

Route::put('courses/{course}/bookmarks', 'Teacher\CourseController@bookmarks')->name('courses.bookmarks')->middleware('throttle:30,1');

app/Http/Controllers/Client/ProfileController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\View\View;
use Illuminate\Routing\Redirector;
use App\Http\Requests\StoreProfile;
use App\Http\Requests\UpdateProfile;
use App\Models\AbilityClient;
use App\Models\ClientProfile;
use App\Models\CourseCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use Illuminate\Http\RedirectResponse;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\Foundation\Application;

class ProfileController extends Controller {

    /**
     * Display data from profile
     *
     * @param Request $request
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $profile = ClientProfile::where('client_id', Auth::id())->first();
        if ($profile) {
            return view('client.profile.index', compact('profile'));
        }

        return redirect(route('profile.create'));

    }

    /**
     * Show the form for creating the profile.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $profile = ClientProfile::where('client_id', Auth::id())->exists();
        $categories = CourseCategory::all();
        if (!$profile) {
            return view('client.profile.create', compact('categories'));
        }

        return redirect(route('profile.index'));
    }

    /**
     * Store the profile.
     *
     * @param StoreProfile $request
     * @return Application|Factory|View
     */
    public function store(StoreProfile $request)
    {
        $validated = $request->validated();

        //check if profile already exist
        $profile = ClientProfile::where('client_id', Auth::id())->exists();
        if ($profile) {
            return view('client.profile.index', compact('profile'));
        }

        foreach ($validated['abilities'] as $ability) {
            AbilityClient::create(['client_id' => Auth::id(), 'course_categories_id' => $ability]);
        }
        unset($validated['abilities']);

        $fileNameToStore = time() . '.' . $request->file('photo')->getClientOriginalExtension();
        $path = '/storage/avatars/clients/' . $fileNameToStore;

        Image::make($request->file('photo'))->resize(300, 300)->save(public_path($path));
        $validated['photo'] = $path;

        ClientProfile::create($validated + ['client_id' => Auth::id()]);

        return redirect(route('profile.index'));
    }


    /**
     * Show the form for editing the profile.
     *
     * @return Application|RedirectResponse|Redirector
     */
    public function edit()
    {
        $profile = ClientProfile::where('client_id', Auth::id())->first();
        $categories = CourseCategory::all();
        $activeCategories = $profile->client->categories;

        if (!$profile) {
            return redirect(route('profile.create'));
        }

        return view('client.profile.edit', compact('profile', 'categories', 'activeCategories'));
    }

    /**
     * Update the profile.
     *
     * @param UpdateProfile $request
     * @return Application|Factory|View
     */
    public function update(UpdateProfile $request)
    {
        $validated = $request->validated();

        $clientId = Auth::id();
        AbilityClient::where('client_id', $clientId)->delete();

        $newAbilities = $validated['abilities'];
        foreach ($newAbilities as $ability) {
            AbilityClient::create(['client_id' => $clientId, 'course_categories_id' => $ability]);
        }
        unset($validated['abilities']);

        $profile = ClientProfile::where('client_id', Auth::id())->first();
        $profile->update($validated);

        return view('client.profile.index', compact('profile'));
    }

    /**
     * @param Request $request
     */
    public function updatePhoto(Request $request)
    {
        //update photo and delete old
    }
}

app/Http/Controllers/Client/TeacherController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\View\View;
use Illuminate\Http\Response;
use App\Models\TeacherProfile;
use App\Models\TeacherRequests;
use Illuminate\Http\JsonResponse;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Contracts\View\Factory;
use Illuminate\Validation\ValidationException;
use Illuminate\Contracts\Foundation\Application;

class TeacherController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $teachers = TeacherProfile::getPublicTeachers();
        $requests = TeacherRequests::getRequestsByClientId(Auth::id());

        return view('client.teachers.index', compact(['teachers','requests']));
    }

    /**
     * Display the specified resource.
     *
     * @param TeacherProfile $teacher
     * @return Application|Factory|View
     */
    public function show(TeacherProfile $teacher)
    {
        return view('client.teachers.show', compact('teacher'));
    }


    /**
     * add request to teacher
     *
     * @param Request $request
     * @return JsonResponse
     * @throws ValidationException
     */
    public function requestToTeacher(Request $request)
    {
        $validated = $this->validate($request, [
            'teacher_id' => 'required|integer',
            'message' => 'nullable',
        ]);

        $teacherRequest = TeacherRequests::create($validated + ['client_id' => Auth::id()]);

        return response()->json($teacherRequest);
    }
}

app/Http/Controllers/Teacher/CabinetController.php
<?php

namespace App\Http\Controllers\Teacher;

use Illuminate\View\View;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\Factory;

class CabinetController extends Controller {

    /**
     * @return Factory|View
     */
    public function index()
    {
        return view('teacher.cabinet');
    }
}

app/Http/Controllers/Teacher/ChapterController.php
<?php

namespace App\Http\Controllers\Teacher;

use App\Traits\ChangeOrderTrait;
use App\Http\Controllers\Controller;
use App\Models\Chapter;
use Illuminate\Http\Request;
use App\Http\Requests\Teacher\ChangeOrderRequest;

class ChapterController extends Controller {

    use ChangeOrderTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            'title' => 'required|min:3',
            'course_id' => 'required|integer',
        ]);

        return Chapter::create($validated + ['display_order' => Chapter::getNextDisplayOrder($validated['course_id'])]);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Chapter $chapter
     * @return \Illuminate\Http\Response
     */
    public function show(Chapter $chapter)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Chapter $chapter
     * @return \Illuminate\Http\Response
     */
    public function edit(Chapter $chapter)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Chapter      $chapter
     * @return Chapter
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Chapter $chapter)
    {
        $validated = $this->validate($request, [
            'title' => 'required|min:3',
        ]);
        $chapter->update($validated);

        return $chapter;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Chapter $chapter
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Chapter $chapter)
    {
        $result = $chapter->delete();

        return response()->json($result);
    }

    /**
     * change order for the chapter
     *
     * @param ChangeOrderRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function changeOrder(ChangeOrderRequest $request)
    {
        $validated = $request->validated();

        if ($validated['old_order'] === $validated['new_order']) {
            return response()->json(false, 200);
        }

        if ($validated['old_order'] > $validated['new_order']) {
            $chapters = Chapter::getChaptersBetweenOrders($validated['new_order'], $validated['old_order'], $validated['key_id']);

            $chapters = $this->changeOrderToTop($chapters, $validated);
        } else {
            $chapters = Chapter::getChaptersBetweenOrders($validated['old_order'], $validated['new_order'], $validated['key_id']);

            $chapters = $this->changeOrderToBottom($chapters, $validated);
        }

        return response()->json($chapters, 201);
    }
}

resources/views/teacher/profile/create.blade.php
@extends('layouts.teacher')

@section('content')
{{--    <form action="{{route('teacher.profile.store')}}" method="POST" enctype="multipart/form-data">--}}
{{--        @csrf--}}
{{--        <div class="row">--}}
{{--            <div class="cart cart-50">--}}
{{--                <div class="row">--}}
{{--                    <div class="col-25 v-center">--}}
{{--                        <div class="form-group @error('photo') is-invalid @enderror">--}}
{{--                            <div class="avatar-upload-btn b-center" id="teacher-photo-container"--}}
{{--                                 onclick="chooseTeacherProfilePhoto();">--}}
{{--                                <img class="default" src="{{asset('img/default_user.svg')}}" alt="">--}}
{{--                                <img class="uploaded" src="" alt="">--}}
{{--                                --}}{{--                                <img class="sm_photo" src="{{asset('img/icons/icons-camera.svg')}}" alt="">--}}
{{--                            </div>--}}
{{--                            @error('photo')--}}
{{--                            <div class="invalid-feedback center">{{ $message }}</div>--}}
{{--                            @enderror--}}

{{--                            <input type="file"--}}
{{--                                   class="form-control-file"--}}
{{--                                   id="teacher-photo"--}}
{{--                                   name="photo"--}}
{{--                                   accept="image/x-png,image/jpg,image/jpeg"--}}
{{--                            >--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                    <div class="col-75 v-center">--}}
{{--                        <div class="row">--}}
{{--                            <div class="col-50">--}}
{{--                                <div class="form-group @error('first_name') is-invalid @enderror">--}}
{{--                                    <label for="teacher_fname">{{__('profile.first_name')}}</label>--}}
{{--                                    <input id="teacher_fname" name="first_name" class="form-field"--}}
{{--                                           required type="text"--}}
{{--                                           value="{{ old('first_name') }}">--}}

{{--                                    @error('first_name')--}}
{{--                                    <div class="invalid-feedback">{{ $message }}</div>--}}
{{--                                    @enderror--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            <div class="col-50">--}}
{{--                                <div class="form-group @error('last_name') is-invalid @enderror">--}}
{{--                                    <label for="teacher_lname">{{__('profile.last_name')}}</label>--}}
{{--                                    <input type="text" name="last_name" class="form-field"--}}
{{--                                           required id="teacher_lname" value="{{ old('last_name') }}">--}}

{{--                                    @error('last_name')--}}
{{--                                    <div class="invalid-feedback">{{ $message }}</div>--}}
{{--                                    @enderror--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="row">--}}
{{--                            <div class="col-50">--}}
{{--                                <div class="form-group @error('degree') is-invalid @enderror">--}}
{{--                                    <label for="teacher_degree">{{__('profile.degree')}}</label>--}}
{{--                                    <input type="text" name="degree" class="form-field" required--}}
{{--                                           id="teacher_degree" value="{{ old('degree') }}">--}}

{{--                                    @error('degree')--}}
{{--                                    <div class="invalid-feedback">{{ $message }}</div>--}}
{{--                                    @enderror--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            <div class="col-50">--}}
{{--                                <div class="form-group @error('phone') is-invalid @enderror">--}}
{{--                                    <label for="teacher_phone">{{__('profile.phone')}}</label>--}}
{{--                                    <input id="teacher_phone" name="phone" class="form-field"--}}
{{--                                           type="text" value="{{ old('photo') }}">--}}

{{--                                    @error('phone')--}}
{{--                                    <div class="invalid-feedback">{{ $message }}</div>--}}
{{--                                    @enderror--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="row">--}}
{{--                            <div class="col-100">--}}
{{--                                <div class="form-group @error('abilities') is-invalid @enderror">--}}
{{--                                    <label>{{__('profile.chose_skills')}}</label>--}}
{{--                                    <select multiple name="abilities[]"--}}
{{--                                            class="@error('abilities') is-invalid @enderror">--}}
{{--                                        @foreach($teacherCategories as $category)--}}
{{--                                            <option--}}
{{--                                                value="{{$category->id}}" {{ (collect(old('abilities'))->contains($category->id)) ? 'selected':'' }}>{{$category->title}}</option>--}}
{{--                                        @endforeach--}}
{{--                                    </select>--}}

{{--                                    @error('abilities')--}}
{{--                                    <div class="invalid-feedback">{{ $message }}</div>--}}
{{--                                    @enderror--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="row">--}}
{{--                            <div class="col-100">--}}
{{--                                <div class="form-group">--}}
{{--                                    <input class="styled-checkbox" id="styled-checkbox-1" name="is_public"--}}
{{--                                           type="checkbox">--}}
{{--                                    <label for="styled-checkbox-1">{{__('profile.is_public')}}</label>--}}

{{--                                    @error('is_public')--}}
{{--                                    <div class="invalid-feedback">{{ $message }}</div>--}}
{{--                                    @enderror--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div> --}}{{--End cart--}}

{{--            <div class="cart cart-50">--}}
{{--                <div class="row">--}}
{{--                    @foreach(App\Models\Socialmedia::all() as $item)--}}
{{--                        <div class="form-group col-15 social-icon">--}}
{{--                            <img src="{{asset('img/social_icons/' . $item->title . '.svg')}}" alt="">--}}
{{--                        </div>--}}
{{--                        <div class="form-group col-85">--}}
{{--                            <label for="teacher_{{$item->title}}"> {{$item->title}} </label>--}}
{{--                            <input id="teacher_{{$item->title}}" name="social_{{$item->title}}" class="form-field"--}}
{{--                                   value="{{ old('social_' . $item->title) }}" type="text">--}}
{{--                        </div>--}}
{{--                    @endforeach--}}
{{--                </div>--}}
{{--            </div> --}}{{--End cart--}}
{{--            <div class="cart cart-100">--}}
{{--                <div class="form-group @error('about_me') is-invalid @enderror">--}}
{{--                    <label for="content">{{__('profile.personal_info')}}</label>--}}
{{--                    <div id="create-profile-toolbar-container"></div>--}}

{{--                    <textarea id="about_me_textarea" class="d-none" name="about_me">{{old('about_me')}}</textarea>--}}

{{--                    <div id="create-profile-content"></div>--}}

{{--                    @error('about_me')--}}
{{--                    <div class="invalid-feedback">{{ $message }}</div>--}}
{{--                    @enderror--}}
{{--                </div>--}}

{{--                <div class="form-group text-center b-center">--}}
{{--                    <button type="submit" id="submit_profile_teacher"--}}
{{--                            class="btn b-center">{{__('profile.save_btn')}}</button>--}}
{{--                </div>--}}
{{--            </div> --}}{{--End cart--}}
{{--        </div>--}}
{{--    </form>--}}

    <profile-create></profile-create>

@endsection

@section('vue')
    <script src="{{ asset('js/vue.js') }}"></script>
@endsection


@section('ckeditor')
    <script>

        const inpFile = document.getElementById("teacher-photo");
        const previewContainer = document.getElementById("teacher-photo-container");
        const previewImg = previewContainer.querySelector(".uploaded");
        const defaultImg = previewContainer.querySelector(".default");

        function chooseTeacherProfilePhoto() {
            inpFile.click();
        }

        inpFile.addEventListener("change", function () {
            const file = this.files[0];

            if (file) {
                const reader = new FileReader();

                defaultImg.style.display = "none";
                previewImg.style.display = "flex";

                reader.addEventListener("load", function () {
                    console.log(this);
                    previewImg.setAttribute("src", this.result);
                });

                reader.readAsDataURL(file);
            }
        });
        //
        // ClassicEditor //ClassicEditor //InlineEditor // BalloonEditor // DecoupledEditor
        //     .create( document.querySelector( '#create-profile-content' ) )
        //     .then( editor => {
        //         console.log( editor );
        //     } )
        //     .catch( error => {
        //         console.error( error );
        //     } );

        DecoupledEditor
            .create(document.querySelector('#create-profile-content'))
            .then(editor => {
                const toolbarContainer = document.querySelector('#create-profile-toolbar-container');

                window.editor = editor;
                toolbarContainer.appendChild(editor.ui.view.toolbar.element);

                let textarea = document.getElementById("about_me_textarea");
                editor.setData(textarea.value);
            })
            .catch(error => {
                console.error(error);
            });

        document.getElementById('submit_profile_teacher').onclick = () => {
            document.getElementById('about_me_textarea').value = editor.getData();
        }

    </script>
@endsection

resources/views/teacher/profile/edit.blade.php
@extends('layouts.teacher')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Teacher profile</div>

                    <div class="card-body">
                        <form action="{{route('teacher.profile.update')}}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="teacher-first-name">First name</label>
                                    <input type="text" class="form-control" id="teacher-first-name" name="first_name" value="{{$profile->first_name}}" required>
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="teacher-last-name">Last name</label>
                                    <input type="text" class="form-control" id="teacher-last-name" name="last_name" value="{{$profile->last_name}}" required>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="teacher-degree">Degree</label>
                                    <input type="text" class="form-control" id="teacher-degree" name="degree" value="{{$profile->degree}}" required>
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="teacher-phone">Phone</label>
                                    <input type="text" class="form-control" id="teacher-phone" name="phone" value="{{$profile->phone}}" required>
                                </div>
                            </div>


                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-primary">Change</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection