routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('login/facebook', 'Auth\SocialAuthController@redirect')->name('login.redirect.facebook');
Route::get('login/facebook/callback', 'Auth\SocialAuthController@callback')->name('login.callback.facebook');
Route::get('login/google', 'Auth\SocialAuthController@redirect')->name('login.redirect.google');
Route::get('login/google/callback', 'Auth\SocialAuthController@callback')->name('login.callback.google');
Route::post('login/social/email', 'Auth\SocialAuthController@addEmail')->name('login.social.email');
Route::post('login/telegram', 'Auth\SocialAuthController@addTelegramId')->name('login.telegram');

// teacher
Route::prefix('teachers')->name('teacher.')->group(function() {

    Route::namespace('Teacher')->middleware(['teacher', 'verified'])->group(function() {

        Route::get('profile/create', 'ProfileController@create')->name('profile.create');
        Route::post('profile', 'ProfileController@store')->name('profile.store');

        Route::middleware(['teacher.profile.exist'])->group(function (){

            Route::get('/cabinet', 'CabinetController@index')->name('cabinet.index');
            // profile
            Route::get('profile', 'ProfileController@index')->name('profile.index');
            Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
            Route::put('profile', 'ProfileController@update')->name('profile.update');

            // invite student
            Route::get('invite', 'InviteController@index')->name('invite.index');
            Route::post('invite', 'InviteController@store')->name('invite.store');
            Route::delete('invite/{invite}', 'InviteController@destroy')->name('invite.destroy');

            // student request
            Route::get('students/requests', 'StudentRequestController@index')->name('students.requests.index');
            Route::put('students/requests/{teacherRequests}', 'StudentRequestController@update')->name('students.requests.update');

            // courses
            Route::get('courses/my-courses', 'CourseController@myCourses')->name('courses.my-courses');
            Route::get('courses', 'CourseController@index')->name('courses.index');
            Route::get('courses/create', 'CourseController@create')->name('courses.create');
            Route::get('courses/{course}', 'CourseController@show')->name('courses.show');
            Route::post('courses', 'CourseController@store')->name('courses.store');

            //lessons
            Route::get('courses/{course}/chapters/{chapter}/lessons/create', 'LessonController@create')->name('lessons.create');
            Route::get('courses/{course}/chapters/{chapter}/lessons/{lesson}/edit', 'LessonController@edit')->name('lessons.edit');
            Route::post('courses/{course}/chapters/{chapter}/lessons', 'LessonController@store')->name('lessons.store');
            Route::put('courses/{course}/chapters/{chapter}/lessons/{lesson}', 'LessonController@update')->name('lessons.update');

            // individual lessons themes
            Route::resource('private/themes', 'IndividualLessonThemeController')
                ->only('index', 'store', 'show', 'update', 'destroy')
                ->middleware(['throttle:60,1', 'teacher']);

            // individual lessons
            Route::get('private/lessons', 'IndividualLessonsController@index')->name('individual.index');
            Route::get('private/lessons/create', 'IndividualLessonsController@create')->name('individual.create');
            Route::get('private/lessons/{lesson}/edit', 'IndividualLessonsController@edit')->name('individual.edit');
            Route::put('private/lessons/{lesson}', 'IndividualLessonsController@update')->name('individual.update')->middleware('throttle:30,1');
            Route::post('private/lessons', 'IndividualLessonsController@store')->name('individual.store');
            Route::delete('private/lessons/{lesson}', 'IndividualLessonsController@destroy')->name('individual.destroy');
            Route::post('private/lessons/{lesson}/group', 'IndividualLessonsController@addLessonToGroup')->name('individual.addLessonToGroup');
            Route::post('private/lessons/{lesson}/student', 'IndividualLessonsController@addLessonToStudent')->name('individual.addLessonToStudent');
            Route::put('private/lessons/{lesson}/activate', 'IndividualLessonsController@activate')->name('individual.activate')->middleware('throttle:30,1');
            Route::post('private/lessons/{lesson}/duplicate', 'IndividualLessonsController@duplicate')->name('individual.duplicate')->middleware('throttle:15,1');
            Route::delete('private/lessons/{lesson}/detach/{clientId}', 'IndividualLessonsController@detachStudent')->name('individual.detachStudent')->middleware('throttle:30,1');

            // groups
            Route::get('groups', 'GroupController@index')->name('groups.index');
            Route::post('groups', 'GroupController@store')->name('groups.store');
            Route::put('groups/{group}', 'GroupController@update')->name('groups.update');
            Route::delete('groups/{group}', 'GroupController@destroy')->name('groups.destroy');
            Route::delete('groups/{group}/detach/{clientId}', 'GroupController@detachClient')->name('groups.detachClient');
            Route::post('groups/{group}/attach/{clientId}', 'GroupController@attachClient')->name('groups.attachClient');

            //course lessons
            Route::get('courses/{course}/chapters/{chapter}/lessons/create', 'LessonController@create')->name('lessons.create');
            Route::get('courses/{course}/chapters/{chapter}/lessons/{lesson}/edit', 'LessonController@edit')->name('lessons.edit');
            Route::post('courses/{course}/chapters/{chapter}/lessons', 'LessonController@store')->name('lessons.store');
            Route::put('courses/{course}/chapters/{chapter}/lessons/{lesson}', 'LessonController@update')->name('lessons.update');
        });
    });


    Auth::routes(['verify' => true]);
});

// client
Route::middleware(['client', 'verified'])->namespace('Client')->group(function () {
    Route::get('cabinet', 'CabinetController@index')->name('cabinet.index');

    // profile
    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/create', 'ProfileController@create')->name('profile.create');
    Route::post('profile', 'ProfileController@store')->name('profile.store');
    Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('profile', 'ProfileController@update')->name('profile.update');

    // courses
    Route::get('courses/my-courses', 'CourseController@show')->name('courses.show');
    Route::get('courses', 'CourseController@index')->name('courses.index');

    // teachers
    Route::get('teachers', 'TeacherController@index')->name('teachers.index');
    Route::get('teachers/{teacher}', 'TeacherController@show')->name('teachers.show');
    Route::post('teachers/request', 'TeacherController@requestToTeacher')->name('teachers.requestToTeacher');

    // my-lessons
    Route::get('my-lessons', 'MyLessonController@index')->name('my-lessons.index');
});

Auth::routes(['verify' => true]);

Route::put('courses/{course}/bookmarks', 'Teacher\CourseController@bookmarks')->name('courses.bookmarks')->middleware('throttle:30,1');

app/Http/Controllers/Client/TeacherController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\View\View;
use Illuminate\Http\Response;
use App\Models\TeacherProfile;
use App\Models\TeacherRequests;
use Illuminate\Http\JsonResponse;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Contracts\View\Factory;
use Illuminate\Validation\ValidationException;
use Illuminate\Contracts\Foundation\Application;

class TeacherController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $teachers = TeacherProfile::getPublicTeachers();
        $requests = TeacherRequests::getRequestsByClientId(Auth::id());

        return view('client.teachers.index', compact(['teachers','requests']));
    }

    /**
     * Display the specified resource.
     *
     * @param TeacherProfile $teacher
     * @return Application|Factory|View
     */
    public function show(TeacherProfile $teacher)
    {
        return view('client.teachers.show', compact('teacher'));
    }


    /**
     * add request to teacher
     *
     * @param Request $request
     * @return JsonResponse
     * @throws ValidationException
     */
    public function requestToTeacher(Request $request)
    {
        $validated = $this->validate($request, [
            'teacher_id' => 'required|integer',
            'message' => 'nullable',
        ]);

        $teacherRequest = TeacherRequests::create($validated + ['client_id' => Auth::id()]);

        return response()->json($teacherRequest);
    }
}

app/Http/Controllers/Teacher/CabinetController.php
<?php

namespace App\Http\Controllers\Teacher;

use Illuminate\View\View;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\Factory;

class CabinetController extends Controller {

    /**
     * @return Factory|View
     */
    public function index()
    {
        return view('teacher.cabinet');
    }
}

app/Http/Controllers/Teacher/ChapterController.php
<?php

namespace App\Http\Controllers\Teacher;

use App\Traits\ChangeOrderTrait;
use App\Http\Controllers\Controller;
use App\Models\Chapter;
use Illuminate\Http\Request;
use App\Http\Requests\Teacher\ChangeOrderRequest;

class ChapterController extends Controller {

    use ChangeOrderTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            'title' => 'required|min:3',
            'course_id' => 'required|integer',
        ]);

        return Chapter::create($validated + ['display_order' => Chapter::getNextDisplayOrder($validated['course_id'])]);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Chapter $chapter
     * @return \Illuminate\Http\Response
     */
    public function show(Chapter $chapter)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Chapter $chapter
     * @return \Illuminate\Http\Response
     */
    public function edit(Chapter $chapter)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Chapter      $chapter
     * @return Chapter
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Chapter $chapter)
    {
        $validated = $this->validate($request, [
            'title' => 'required|min:3',
        ]);
        $chapter->update($validated);

        return $chapter;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Chapter $chapter
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Chapter $chapter)
    {
        $result = $chapter->delete();

        return response()->json($result);
    }

    /**
     * change order for the chapter
     *
     * @param ChangeOrderRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function changeOrder(ChangeOrderRequest $request)
    {
        $validated = $request->validated();

        if ($validated['old_order'] === $validated['new_order']) {
            return response()->json(false, 200);
        }

        if ($validated['old_order'] > $validated['new_order']) {
            $chapters = Chapter::getChaptersBetweenOrders($validated['new_order'], $validated['old_order'], $validated['key_id']);

            $chapters = $this->changeOrderToTop($chapters, $validated);
        } else {
            $chapters = Chapter::getChaptersBetweenOrders($validated['old_order'], $validated['new_order'], $validated['key_id']);

            $chapters = $this->changeOrderToBottom($chapters, $validated);
        }

        return response()->json($chapters, 201);
    }
}

app/Http/Controllers/Teacher/CourseController.php
<?php

namespace App\Http\Controllers\Teacher;

use App\Models\Course;
use App\Models\Language;
use App\Models\CourseInfo;
use App\Traits\Image;
use App\Models\CourseCategory;
use App\Models\CourseSubCategory;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Teacher\CourseStoreRequest;

class CourseController extends Controller {

    use Image;

    /**
     * Display a listing of the resource.
     * show all courses
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $courses = Course::getActiveCourses();
        $categories = CourseCategory::all();

        return view('teacher.courses.index', compact(['courses', 'categories']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = CourseCategory::all();
        $languages = Language::all();

        return view('teacher.courses.create', compact(['categories', 'languages']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CourseStoreRequest $request)
    {
        $validated = $request->validated();

        $imagePath = $this->imageUpload($request, 'image', 'img/courses', $this->defaultCourseImage);

        $courseInfo = CourseInfo::create([
            'title' => $validated['title'],
            'description' => $validated['description'],
            'content' => $validated['content'],
        ]);

        $course = Course::create([
            'teacher_id' => Auth::id(),
            'language_id' => 1, // for now it's Ukraine only
            'info_id' => $courseInfo->id,
            'image' => $imagePath,
            'price' => $validated['price'],
            'limit' => $validated['limit'],
        ]);

        $course->subCategory()->attach($validated['sub_category']);

        return redirect()->route('teacher.courses.show', $course->id);
    }

    /**
     * Display the specified resource.
     * show courses for auth teacher
     *
     * @param Course $course
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Course $course)
    {
        $this->authorize('view', $course);

        return view('teacher.courses.show', compact('course'));
    }

    /**
     * Display the specified resource.
     * show courses for auth teacher
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function myCourses()
    {
        $teacherId = Auth::id();

        $courses = Course::getByTeacherId($teacherId);

        return view('teacher.courses.my-courses', compact('courses'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Course $course
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Course $course)
    {
        $result = $course->delete();

        return response()->json($result, 200);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function getSubCategory(Request $request)
    {
        $category = $this->validate($request, [
            'category' => 'integer|required',
        ]);

        return CourseSubCategory::getByCategoryId($category['category']);
    }
}

resources/views/teacher/courses/create.blade.php
@extends('layouts.teacher')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <form method="post" action="{{ route('teacher.courses.store') }}" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="category">{{ __('courses.add.select_category') }}</label>
                        <select class="form-control" id="category" name="category">
                            <option value="">{{ __('courses.add.select_category') }}</option>
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->title }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="sub_category">{{ __('courses.add.select_sub_category') }}</label>
                        <select class="form-control" id="sub_category" name="sub_category[]" multiple></select>

                        @error('sub_category')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="title">{{ __('courses.add.title') }}</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title') }}">

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="description">{{ __('courses.add.description') }}</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" id="description" rows="3" name="description">{{ old('description') }}</textarea>

                        @error('description')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" name="image" accept="image/*">
                            <label class="custom-file-label" for="image">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text" id="image">Image</span>
                        </div>

                        @error('image')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="content">{{ __('courses.add.content') }}</label>
                        <textarea class="form-control" id="create-course-content" rows="3" name="content">{{ old('content') }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="price">{{ __('courses.add.price') }}</label>
                        <input type="number" step="0.01" class="form-control @error('price') is-invalid @enderror" id="price" name="price" value="{{ old('price') }}">

                        @error('price')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="limit">{{ __('courses.add.limit') }}</label>
                        <input type="number" step="1" class="form-control @error('limit') is-invalid @enderror" id="limit" name="limit" value="{{ old('limit') }}">

                        @error('limit')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="language">{{ __('courses.add.select_Language') }}</label>
                        <select class="form-control @error('language') is-invalid @enderror" id="language" name="language" disabled>
                            @foreach($languages as $language)
                                <option value="{{ $language->id }}">{{ $language->name }}</option>
                            @endforeach
                        </select>

                        @error('language')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('ckeditor')
    <script>
        CKEDITOR.replace( 'create-course-content');
    </script>
@endsection

<div id="reg-txt-top" class="panel-row-style panel-row-style-for-w5d51617351ea5-0">
    <div id="pgc-w5d51617351ea5-0-0" class="panel-grid-cell" data-weight="1">
        <div id="panel-w5d51617351ea5-0-0-0" class="so-panel widget widget_sow-editor panel-first-child panel-last-child" data-index="0" data-style="{&quot;id&quot;:&quot;&quot;,&quot;class&quot;:&quot;&quot;,&quot;widget_css&quot;:&quot;&quot;,&quot;mobile_css&quot;:&quot;&quot;,&quot;margin&quot;:&quot;&quot;,&quot;padding&quot;:&quot;&quot;,&quot;mobile_padding&quot;:&quot;&quot;,&quot;background&quot;:&quot;&quot;,&quot;background_image_attachment&quot;:&quot;0&quot;,&quot;background_image_attachment_fallback&quot;:&quot;&quot;,&quot;background_display&quot;:&quot;tile&quot;,&quot;border_color&quot;:&quot;&quot;,&quot;font_color&quot;:&quot;&quot;,&quot;link_color&quot;:&quot;&quot;}">
            <div class="so-widget-sow-editor so-widget-sow-editor-base">
                <div class="siteorigin-widget-tinymce textwidget">
                    <h1 class="reg_b1_ttl">Product registration</h1>
                    <div class="av_warranty_wrap">
                        <p class="av_warranty">Avologi provides limited warranty for Eneo:</p>
                        <p class="reg_b1_txt">Activate your warranty by registering your product <span class="reg_b1_bttxt">within 10 days of purchase</span>. Viable for products bought on Avologi.com and authorized retailers only.</p>
                        <p class="reg_b1_txt">Disclaimer: No warranty is provided for products sold in third party marketplaces except for the products that the brand owners sell directly. </p>
                        <p class="reg_b1_txt">Registering your AVOLOGI purchase links your product with important notifications, proof of ownership, and warranty service.</p>
                        <p class="reg_b1_bttxt">Registration is quick and easy. Just a few steps and you’re done!</p>

                        <ul class="av_warranty_ul">
                            <li>Lifetime limited warranty for ENEO Advanced, ENEO jewelry edition &amp; ENEO Eye Concentrator</li>
                            <li>2 years limited warranty for ENEO Classic</li>
                        </ul>
                    </div>
                    <p class="reg_b1_subtxt title-register_hidden">Why register your AVOLOGI product?</p>

                </div>
            </div>
        </div>
    </div>
</div>

resources/views/teacher/courses/index.blade.php
@extends('layouts.teacher')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <courses-list
                    :categories-data="{{ json_encode($categories) }}"
                    :courses-data="{{ json_encode($courses) }}">

                </courses-list>
            </div>
        </div>
    </div>
@endsection
@section('vue')

    <script src="{{ asset('js/vue.js') }}"></script>

@endsection

resources/views/teacher/courses/my-courses.blade.php
@extends('layouts.teacher')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="my-2">
                <a href="{{ route('teacher.courses.create') }}">
                    <button class="btn btn-dark">{{ __('courses.add_course') }}</button>
                </a>
            </div>
            <div class="col-md-12">
                <div class="row">
                    @foreach($courses as $course)
                        <div class="col-sm-6 mb-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">{{$course->info->title}}</h5>
                                    <p class="card-text">{{$course->info->description}}</p>
                                    <p class="card-text">Lang : {{$course->language->name}}</p>
                                    <a href="{{ route('teacher.courses.show', $course->id) }}" class="btn btn-primary">
                                        {{ __('courses.link_to_course') }}
                                    </a>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/teacher/courses/show.blade.php
@extends('layouts.teacher')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-11">
                <div class="media">
                    <img src="{{ asset($course->image) }}" width="200" class="mr-3 img-thumbnail" alt="{{ $course->info->title }}">
                    <div class="media-body">
                        <h5 class="mt-0">{{ $course->info->title }}</h5>
                        <p>
                            desc: {{ $course->info->description }}
                        </p>
                        <p>
                            created: {{ $course->created_at->format('d-m-Y') }}
                        </p>
                        <p>
                            sub categories:
                            @foreach($course->subCategory as $category)
                                <span>{{$category->title}}</span>
                            @endforeach
                        </p>
                        <p>
                            category: {{ $course->category->title }}
                        </p>
                        <p>
                            language: {{ $course->language->name }}
                        </p>
                        <p>
                            price: {{ $course->price }}
                        </p>
                        <p>
                            limit: {{ $course->limit }}
                        </p>
                        <p>
                            Active: {{ $course->is_active ? 'Yes' : 'No' }}
                        </p>
                    </div>
                </div>
                <div class="my-3">
                    <h3 class="text-center">Content</h3>
                    <div>
                        {!! $course->info->content !!}
                    </div>
                </div>
            </div>
            <div class="col-md-1">
                <button id="delete_course" data-course-id="{{ $course->id }}" class="btn btn-danger">Delete</button>
                <a href="#" class="btn btn-warning">Edit</a>
            </div>
        </div>

    </div>

    <chapters class="mt-3" :course-data="{{ json_encode($course) }}"></chapters>

@endsection

@section('vue')

    <script src="{{ asset('js/vue.js') }}"></script>

@endsection